#!/usr/bin/env bash
if [[ "$(defaults read com.apple.finder CreateDesktop)" == "0" ]]; then
  defaults write com.apple.finder CreateDesktop -bool TRUE
else
  defaults write com.apple.finder CreateDesktop -bool FALSE
fi
killall Finder
